name: Publish to PyPI

on:
  workflow_dispatch:


jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/clubbi_utils
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pipenv'
      - id: install-pipenv
        run: |
          python -m pip install --upgrade pip pipenv
      - name: Install dependencies
        run: |
          pipenv sync --dev
      - name: Build
        run: |
          pipenv run build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
