name: Run Unit Tests In Any Push

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: true
      
      - id: install-pipenv
        run: |
          python -m pip install --upgrade pip pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev

      - name: Docker
        run: |
          docker-compose up -d localstack postgres
          sleep 10
      
      
      - name: Run mypy
        run: pipenv run mypy -p clubbi_utils -p tests
      
      - name: Run Unit Tests
        run: PYTHONPATH=. pipenv run pytest --cov
