name: Run Unit Tests In Any Push

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - id: install-pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv --version
      
      - id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev

      - name: Docker
        run: |
          docker-compose up -d localstack postgres
          sleep 10
      
      - name: Run mypy
        run: pipenv run mypy -p clubbi_utils -p tests
      
      - name: Run Unit Tests
        run: PYTHONPATH=. pipenv run coverage run -m pytest
